local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   update_frequency: 1.0
   publish_frequency: 1.0
   static_map: true
   rolling_window: false
   width: 5.0
   height: 5.0
   resolution: 10.0
   transform_tolerance: 1.0
   map_type: costmap
